dist:
  name: otelcol-acuvity
  description: OTel Collector distribution including the Acuvity exporter
  output_path: ./otelcol-acuvity

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.127.0
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.127.0
  - gomod: github.com/acuvity/otelexporter v0.1.0
    path: ./

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.127.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.127.0

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.18.0
