// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("acuvity")
	ScopeName = "github.com/acuvity/otelexporter"
)

const (
	TracesStability = component.StabilityLevelAlpha
)
